-- Aggiungi colonne mancanti alla tabella business_plans

ALTER TABLE business_plans 
ADD COLUMN IF NOT EXISTS client_name TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS project_type TEXT DEFAULT 'hotel',
ADD COLUMN IF NOT EXISTS num_rooms INTEGER DEFAULT 90,
ADD COLUMN IF NOT EXISTS stars INTEGER DEFAULT 4,
ADD COLUMN IF NOT EXISTS has_spa BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS has_restaurant BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS opening_days_year INTEGER DEFAULT 365,
ADD COLUMN IF NOT EXISTS projection_years INTEGER DEFAULT 3,
ADD COLUMN IF NOT EXISTS start_year INTEGER DEFAULT 2026;
