const { Client } = require("pg")
;(async () => {
  const c = new Client({ connectionString: process.env.POSTGRES_URL_NON_POOLING })
  await c.connect()
  const r = await c.query("select pg_get_constraintdef(oid) as def from pg_constraint where conname='ecomobility_devices_device_type_check'")
  console.log("constraint:", r.rows)
  const r2 = await c.query("select distinct device_type from ecomobility_devices")
  console.log("existing:", r2.rows)
  await c.end()
})()
